---
- name: copy IntelliJ Idea settings file
  ansible.builtin.copy:
    src: intellij-mac.zip
    dest: "{{ macos_download_path }}"

- name: copy WebStorm settings file
  ansible.builtin.copy:
    src: webstorm-mac.zip
    dest: "{{ macos_download_path }}"

- name: copy Android Studio settings file
  ansible.builtin.copy:
    src: androidstudio-mac.zip
    dest: "{{ macos_download_path }}"

- name: ensures UltraEdit settings files path exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Library/Application Support/UltraEdit"
    state: directory

- name: copy UltraEdit settings files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/Library/Application Support/UltraEdit"
  with_items:
    - uex.conf
    - uex.conf_vol
    - Uex.tb0
    - ultraedit.spl
    - UltraEdit.uek
